load(
    "@rules_scala_annex//rules:scala.bzl",
    "scala_binary",
)

scala_binary(
    name = "example",
    srcs = [
        "main.scala",
    ],
    deps = [
        "@scala_2_12//:dev_zio_zio_2_12"
    ],
    )
