create table TODO_LISTS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

create table TODO_ITEMS(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    LIST_ID INT NOT NULL,
    COMPLETED BOOL DEFAULT TRUE
);

create table NOTES(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL
);
